# Generated by Django 3.0.1 on 2021-07-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210715_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='second_adress',
            new_name='email',
        ),
    ]
